package Model;
// Generated Jul 15, 2020 9:40:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="Account"
    ,schema="dbo"
    ,catalog="ShopHoaThachKimTest"
    , uniqueConstraints = @UniqueConstraint(columnNames="Phone") 
)
public class Account  implements java.io.Serializable {


     private String tenDangNhap;
     private String matKhau;
     private String email;
     private String phone;
     private String diaChi;
     private String tenKhachHang;
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public Account() {
    }

    public Account(String tenDangNhap, String matKhau, String email, String phone, String diaChi, String tenKhachHang) {
        this.tenDangNhap = tenDangNhap;
        this.matKhau = matKhau;
        this.email = email;
        this.phone = phone;
        this.diaChi = diaChi;
        this.tenKhachHang = tenKhachHang;
    }

    
	
    public Account(String tenDangNhap, String matKhau) {
        this.tenDangNhap = tenDangNhap;
        this.matKhau = matKhau;
    }
    public Account(String tenDangNhap, String matKhau, String email, String phone, String diaChi, String tenKhachHang, Set<HoaDon> hoaDons) {
       this.tenDangNhap = tenDangNhap;
       this.matKhau = matKhau;
       this.email = email;
       this.phone = phone;
       this.diaChi = diaChi;
       this.tenKhachHang = tenKhachHang;
       this.hoaDons = hoaDons;
    }
   
     @Id 

    
    @Column(name="TenDangNhap", unique=true, nullable=false)
    public String getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(String tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }

    
    @Column(name="MatKhau", nullable=false)
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Phone", unique=true)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="DiaChi")
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="TenKhachHang")
    public String getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(String tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }

    @Override
    public String toString() {
        return "Account{" + "tenDangNhap=" + tenDangNhap + ", matKhau=" + matKhau + ", email=" + email + ", phone=" + phone + ", diaChi=" + diaChi + ", tenKhachHang=" + tenKhachHang + '}';
    }

    


}


