package Model;
// Generated Jul 15, 2020 9:40:27 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiethoadon generated by hbm2java
 */
@Entity
@Table(name="CHITIETHOADON"
    ,schema="dbo"
    ,catalog="ShopHoaThachKimTest"
)
public class Chitiethoadon  implements java.io.Serializable {


     private ChitiethoadonId id;
     private HoaDon hoaDon;
     private SanPham sanPham;
     private Integer soLuong;

    public Chitiethoadon() {
    }

	
    public Chitiethoadon(ChitiethoadonId id, HoaDon hoaDon, SanPham sanPham) {
        this.id = id;
        this.hoaDon = hoaDon;
        this.sanPham = sanPham;
    }
    public Chitiethoadon(ChitiethoadonId id, HoaDon hoaDon, SanPham sanPham, Integer soLuong) {
       this.id = id;
       this.hoaDon = hoaDon;
       this.sanPham = sanPham;
       this.soLuong = soLuong;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maHoaDon", column=@Column(name="MaHoaDon", nullable=false) ), 
        @AttributeOverride(name="maSanPham", column=@Column(name="MaSanPham", nullable=false) ) } )
    public ChitiethoadonId getId() {
        return this.id;
    }
    
    public void setId(ChitiethoadonId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaHoaDon", nullable=false, insertable=false, updatable=false)
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaSanPham", nullable=false, insertable=false, updatable=false)
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }

    
    @Column(name="SoLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


