package Model;
// Generated Jul 15, 2020 9:40:27 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitiethoadonId generated by hbm2java
 */
@Embeddable
public class ChitiethoadonId  implements java.io.Serializable {


     private String maHoaDon;
     private String maSanPham;

    public ChitiethoadonId() {
    }

    public ChitiethoadonId(String maHoaDon, String maSanPham) {
       this.maHoaDon = maHoaDon;
       this.maSanPham = maSanPham;
    }
   


    @Column(name="MaHoaDon", nullable=false)
    public String getMaHoaDon() {
        return this.maHoaDon;
    }
    
    public void setMaHoaDon(String maHoaDon) {
        this.maHoaDon = maHoaDon;
    }


    @Column(name="MaSanPham", nullable=false)
    public String getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitiethoadonId) ) return false;
		 ChitiethoadonId castOther = ( ChitiethoadonId ) other; 
         
		 return ( (this.getMaHoaDon()==castOther.getMaHoaDon()) || ( this.getMaHoaDon()!=null && castOther.getMaHoaDon()!=null && this.getMaHoaDon().equals(castOther.getMaHoaDon()) ) )
 && ( (this.getMaSanPham()==castOther.getMaSanPham()) || ( this.getMaSanPham()!=null && castOther.getMaSanPham()!=null && this.getMaSanPham().equals(castOther.getMaSanPham()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaHoaDon() == null ? 0 : this.getMaHoaDon().hashCode() );
         result = 37 * result + ( getMaSanPham() == null ? 0 : this.getMaSanPham().hashCode() );
         return result;
   }   


}


