package Model;
// Generated Jul 15, 2020 9:40:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name="HoaDon"
    ,schema="dbo"
    ,catalog="ShopHoaThachKimTest"
)
public class HoaDon  implements java.io.Serializable {


     private String maHoaDon;
     private Account account;
     private Date ngayTao;
     private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

    public HoaDon() {
    }

	
    public HoaDon(String maHoaDon, Account account, Date ngayTao) {
        this.maHoaDon = maHoaDon;
        this.account = account;
        this.ngayTao = ngayTao;
    }
    public HoaDon(String maHoaDon, Account account, Date ngayTao, Set<Chitiethoadon> chitiethoadons) {
       this.maHoaDon = maHoaDon;
       this.account = account;
       this.ngayTao = ngayTao;
       this.chitiethoadons = chitiethoadons;
    }
   
     @Id 

    
    @Column(name="MaHoaDon", unique=true, nullable=false)
    public String getMaHoaDon() {
        return this.maHoaDon;
    }
    
    public void setMaHoaDon(String maHoaDon) {
        this.maHoaDon = maHoaDon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TenDangNhap", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayTao", nullable=false, length=10)
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hoaDon")
    public Set<Chitiethoadon> getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }

    @Override
    public String toString() {
        return "HoaDon{" + "maHoaDon=" + maHoaDon + ", account=" + account + ", ngayTao=" + ngayTao + '}';
    }




}


