package Model;
// Generated Jul 15, 2020 9:40:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name="SanPham"
    ,schema="dbo"
    ,catalog="ShopHoaThachKimTest"
)
public class SanPham  implements java.io.Serializable {


     private String maSanPham;
     private NguonCap nguonCap;
     private String sanPhamName;
     private String loaiSanPham;
     private int giaNiemYet;
     private Integer tongSoLuong;
     private String trangThai;
     private String url;
     private String description;
     private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

    public SanPham() {
    }

	
    public SanPham(String maSanPham, NguonCap nguonCap, String sanPhamName, int giaNiemYet) {
        this.maSanPham = maSanPham;
        this.nguonCap = nguonCap;
        this.sanPhamName = sanPhamName;
        this.giaNiemYet = giaNiemYet;
    }

    public SanPham(String maSanPham, NguonCap nguonCap, String sanPhamName, String loaiSanPham, int giaNiemYet, Integer tongSoLuong, String trangThai, String url) {
        this.maSanPham = maSanPham;
        this.nguonCap = nguonCap;
        this.sanPhamName = sanPhamName;
        this.loaiSanPham = loaiSanPham;
        this.giaNiemYet = giaNiemYet;
        this.tongSoLuong = tongSoLuong;
        this.trangThai = trangThai;
        this.url = url;
    }
    
    
    
    public SanPham(String maSanPham, NguonCap nguonCap, String sanPhamName, String loaiSanPham, int giaNiemYet, Integer tongSoLuong, String trangThai, String url, String description, Set<Chitiethoadon> chitiethoadons) {
       this.maSanPham = maSanPham;
       this.nguonCap = nguonCap;
       this.sanPhamName = sanPhamName;
       this.loaiSanPham = loaiSanPham;
       this.giaNiemYet = giaNiemYet;
       this.tongSoLuong = tongSoLuong;
       this.trangThai = trangThai;
       this.url = url;
       this.description = description;
       this.chitiethoadons = chitiethoadons;
    }
   
     @Id 

    
    @Column(name="MaSanPham", unique=true, nullable=false)
    public String getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NguonCapID", nullable=false)
    public NguonCap getNguonCap() {
        return this.nguonCap;
    }
    
    public void setNguonCap(NguonCap nguonCap) {
        this.nguonCap = nguonCap;
    }

    
    @Column(name="SanPhamName", nullable=false)
    public String getSanPhamName() {
        return this.sanPhamName;
    }
    
    public void setSanPhamName(String sanPhamName) {
        this.sanPhamName = sanPhamName;
    }

    
    @Column(name="LoaiSanPham")
    public String getLoaiSanPham() {
        return this.loaiSanPham;
    }
    
    public void setLoaiSanPham(String loaiSanPham) {
        this.loaiSanPham = loaiSanPham;
    }

    
    @Column(name="GiaNiemYet", nullable=false)
    public int getGiaNiemYet() {
        return this.giaNiemYet;
    }
    
    public void setGiaNiemYet(int giaNiemYet) {
        this.giaNiemYet = giaNiemYet;
    }

    
    @Column(name="TongSoLuong")
    public Integer getTongSoLuong() {
        return this.tongSoLuong;
    }
    
    public void setTongSoLuong(Integer tongSoLuong) {
        this.tongSoLuong = tongSoLuong;
    }

    
    @Column(name="TrangThai")
    public String getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    
    @Column(name="Url")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sanPham")
    public Set<Chitiethoadon> getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }

    @Override
    public String toString() {
        return "SanPham{" + "maSanPham=" + maSanPham + ", nguonCap=" + nguonCap + ", sanPhamName=" + sanPhamName + ", loaiSanPham=" + loaiSanPham + ", giaNiemYet=" + giaNiemYet + ", tongSoLuong=" + tongSoLuong + ", trangThai=" + trangThai + ", url=" + url + ", description=" + description + '}';
    }




}


